### ISSUE TITLE
Build file is enormous

### ISSUE THREAD

**Issue by bence-toth** [bence-toth/covid-charts#17]
This is probably due to the new dependencies introduced

**Comment by bancho22** [comment]
I believe I found the culprit

https://github.com/simonepri/country-iso/blob/master/fixtures/cities.geo.json

Google offers an API for this but it requires an API key

https://developers.google.com/maps/documentation/geocoding/overview?csw=1#ReverseGeocoding

**Comment by bence-toth** [comment]
> I believe I found the culprit
> 
> https://github.com/simonepri/country-iso/blob/master/fixtures/cities.geo.json
> 
> Google offers an API for this but it requires an API key
> 
> https://developers.google.com/maps/documentation/geocoding/overview?csw=1#ReverseGeocoding

How about this?

https://www.bigdatacloud.com/geocoding-apis/free-reverse-geocode-to-city-api

**Comment by bancho22** [comment]
I also found this one 😆 
https://nominatim.org/release-docs/develop/api/Reverse/

I'll look into both

**Comment by bence-toth** [comment]
I think Google is not an option since we can't expose an API key

**Comment by bancho22** [comment]
The one you shared looks really good.
